### PR TITLE
Fix workspace variable handling

### PR DESCRIPTION
**Pull request by jdkato**

### CODE REVIEW

**Review by emmenko — COMMENTED** [review]
Thanks, changes look good from what I can see.

Only the README needs to be updated (there was also a typo). See https://github.com/errata-ai/vale-vscode/pull/22/files#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by ChrisChinchilla** [comment]
Ahh right, i think we removed the workspace functionality, but left it in the doc. @jdkato I feel like we discussed not to include workspace folders in the extension, but I guess the issue #21 is enough of a valid use case?

**Comment by jdkato** [comment]
@ChrisChinchilla: we changed the *linting* behavior to only open files (vs the entire workspace), but this PR relates only to the handling of settings with `${workspaceFolder}` in their value.

**Comment by emmenko** [comment]
Thanks again for fixing this. Do you have an ETA when the bugfix can be released?

**Pull request merged**
