### PR TITLE
Move readability checks to status bar

### LINKED ISSUE #13: Add readability score to status bar
Transferred from https://github.com/testthedocs/vscode-vale/issues/24

If the config file/styles have readability scores enabled, move the output to the status bar instead of buried at the top of the file.

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
Closes #13 I think this could do with polish, and possibly a setting option. I also opted to remove the readability check from the alerts array to reduce duplication. The check always seemed to be first, but maybe this is a little brittle, I am open to alternatives.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
A little code tidying needed too

**Comment by jdkato** [comment]
This looks like a generally good approach, but I would move the conditional into the `for-loop`to avoid depending on the alert ordering:

```js
for (var i = 0; i < alerts.length; ++i) {
  if (alerts[i].Match === "") {
    var readabilityMessage = alerts[0].Message;
    // TODO: It seemed a good idea to remove the item if it exists, but don't need to.
    this.updateStatusBarItem(readabilityMessage);
  } else {
    let diagnostic = toDiagnostic(alerts[i], this.stylesPath, backend);
    let key = `${diagnostic.message}-${diagnostic.range}`;
    this.alertMap[key] = alerts[i];

    diagnostics.push(diagnostic);
  }
}
```

**Comment by ChrisChinchilla** [comment]
Seems reasonable. What were your thoughts on the `array.splice`? It seemed tidier, but not essential.

**Comment by jdkato** [comment]
It shouldn't be necessary anymore since diagnostics are only created for alerts that don't meet the condition in the for loop.

**Comment by ChrisChinchilla** [comment]
OK @jdkato removed that line!

**Pull request merged**
